### PR TITLE
Django 1.8 deprecation fix.

### PR DESCRIPTION
**Pull request by misread**
SortedDict is planned to be removed in Django 1.9, and has been replaced with OrderedDict.

### CODE REVIEW

**Comment by samuraisam** [comment]
What django version compatibility does this have when this fix is applied?

**Comment by misread** [comment]
I know for a fact at least 1.7 and up. I haven't gotten around to testing it without outdated versions yet.

**Comment by samuraisam** [comment]
I would like to support at least 1.6 in the app, if we can support down to 1.6 I can merge this.

**Comment by samuraisam** [comment]
Fixed in another PR

**Pull request closed without merging**
